name: Build Android APK
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Deep clean broken dependency
        run: |
          find . -type f \( -name "*.gradle*" -o -name "*.toml" -o -name "*.kt" -o -name "*.java" \) -exec sed -i -e '/amitshekhar/d' -e '/debug-db/d' -e '/debugDb/d' -e '/DebugDB/d' -e '/debug\.db/d' {} + || true
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build APK
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: iOS17-Launcher
          path: app/build/outputs/apk/debug/*.apk
